### ISSUE TITLE
Rename root package from "tesseract" to "tesseract_robotics"

### ISSUE THREAD

**Issue by johnwason** [tesseract-robotics/tesseract_python#13]
There is another project out there named "tesseract" that has taken the root namespace `tesseract` on PyPI and other package managers. Currently all of the modules in Python for tesseract robotics have names like `tesseract.tesseract_common`, `tesseract.tesseract_geometry`, etc. Renaming to something `tesseract_robotics.tesseract_common` and `tesseract_robotics.tesseract_geometry` would help get around this issue.

@Levi-Armstrong @mpowelson any thoughts?

**Comment by Levi-Armstrong** [comment]
That works for me. That is also the name I used on anaconda so it aligns. @mpowelson what do you think?

**Comment by mpowelson** [comment]
Fine by me.

**Comment by johnwason** [comment]
Completed in #16
