### ISSUE TITLE
Documentation Pages are Down

### ISSUE THREAD

**Issue by fishbotics** [tesseract-robotics/tesseract_python#22]
Hi all, 

I'm super interested in this project! Especially the direct Python bindings. I'd like to try out the bindings (and hopefully contribute to them!) but I'm not sure how to get started. The documentation page is down. 

What steps would you suggest to build and view the docs in order to get started with the Python bindings?

**Comment by johnwason** [comment]
Hi @fishbotics, unfortunately we don't have any Python specific documentation. The Python wrappers are nearly identical to the C++ wrappers, so for the most part you can use the C++ wrappers for reference. Take a look at the "test" directory for examples of how to use the Python interface.

**Comment by johnwason** [comment]
See #1

**Comment by johnwason** [comment]
Documentation is now available! See https://tesseract-robotics.github.io/tesseract_python/
