### ISSUE TITLE
Missing tesseract_command_language/core/serialization.h file when building Python interface

### ISSUE THREAD

**Issue by fishbotics** [tesseract-robotics/tesseract_python#24]
Moving issue from `tesseract_planning` repo to here: https://github.com/tesseract-robotics/tesseract_planning/issues/206

Hi all, 

When I try to build the Python interface, I get the following error: 
```
tesseract_ws/src/tesseract_python/tesseract_python/swig/tesseract_command_language_python.i:98: Error: Unable to find 'tesseract_command_language/core/serialization.h'
```

It looks like `serialization.cpp` still exists in the `src` directory (https://github.com/tesseract-robotics/tesseract_planning/blob/master/tesseract_command_language/src/core/serialization.cpp) but is missing from the include directory as of  https://github.com/tesseract-robotics/tesseract_planning/commit/59cb07667c44fd22d2a81e7f7966a475b0d3c465

Should this file be removed from the Python interface as well? https://github.com/tesseract-robotics/tesseract_python/blob/master/tesseract_python/swig/tesseract_command_language_python.i#L41

Thanks!

**Comment by fishbotics** [comment]
I haven't used SWIG before, so I'm taking stabs in the dark here but I tried deleting lines 41 and 98 in https://github.com/tesseract-robotics/tesseract_python/blob/master/tesseract_python/swig/tesseract_command_language_python.i (the lines referencing the old serialization file) and rebuilding and I get a ton of errors that are maybe related and maybe not.

For example, 
```/home/fishy/tesseract_ws/devel/include/tesseract_common/types.h:248: Error: Syntax error in input(1).                                                                                                  
make[2]: *** [CMakeFiles/tesseract_command_language_python_swig_compilation.dir/build.make:64: CMakeFiles/_tesseract_command_language_python.dir/tesseract_command_language_pythonPYTHON.stamp] Error 1
make[2]: *** Deleting file 'CMakeFiles/_tesseract_command_language_python.dir/tesseract_command_language_pythonPYTHON.stamp'                                                                           
make[1]: *** [CMakeFiles/Makefile2:1046: CMakeFiles/tesseract_command_language_python_swig_compilation.dir/all] Error 2                                                                                
```

I didn't make any changes to that `types.h` file (it's not even in the `src` directory), but the line that it's complaining about is (marked below with `>>>>`):

```#include <boost/serialization/export.hpp>
#include <boost/serialization/tracking.hpp>
>>>> BOOST_CLASS_EXPORT_KEY2(tesseract_common::PluginInfo, "PluginInfo")
BOOST_CLASS_EXPORT_KEY2(tesseract_common::PluginInfoContainer, "PluginInfoContainer")
BOOST_CLASS_EXPORT_KEY2(tesseract_common::KinematicsPluginInfo, "KinematicsPluginInfo")
BOOST_CLASS_EXPORT_KEY2(tesseract_common::ContactManagersPluginInfo, "ContactManagersPluginInfo")
BOOST_CLASS_EXPORT_KEY2(tesseract_common::CalibrationInfo, "CalibrationInfo")

**Comment by johnwason** [comment]
@fishbotics 

Unless you are doing something unusual, you should be able to use the version on pip without needing to build from source: https://github.com/tesseract-robotics/tesseract/discussions/754

The current master branch is out of date, we are still working on a few issues before I merge the updates. The current working branch is here: https://github.com/johnwason/tesseract_python-1/tree/pr/UpstreamChanges5

**Comment by fishbotics** [comment]
@johnwason thanks for your help. Maybe this should be a separate issue, but I just tried following the instructions posted here: https://github.com/tesseract-robotics/tesseract/discussions/754

Specifically, I am on Ubuntu 20.04 and I ran

```
sudo apt install python3-pip python3-numpy
python3 -m pip install -U pip
python3 -m pip install --user  tesseract_robotics tesseract_robotics_viewer
git clone --depth=1 https://github.com/tesseract-robotics/tesseract.git
git clone --depth=1 --branch pr/UpstreamChanges5 https://github.com/johnwason/tesseract_python-1.git tesseract_python
export TESSERACT_SUPPORT_DIR=$(pwd)/tesseract/tesseract_support
python3 tesseract_python/tesseract_viewer_python/examples/abb_irb2400_viewer.py
```
When I run this, I get the error:
```
Traceback (most recent call last):
  File "tesseract_python/tesseract_viewer_python/examples/abb_irb2400_viewer.py", line 92, in <module>
    results = flatten(response.getResults().as_CompositeInstruction())
AttributeError: 'ProcessPlanningFuture' object has no attribute 'getResults'
```
Here is an image of the logs:
![image](https://user-images.githubusercontent.com/45679966/176325831-e9f4e69b-3edd-4031-ae39-77f07d61d40d.png)

**Comment by johnwason** [comment]
Yeah check the tests in the update branch above there was a change in the C++ api that flowed down tonpython.

**Comment by fishbotics** [comment]
Ah great, that's a one-line change to modify that results from 

```
results = flatten(response.getResults().as_CompositeInstruction())
```
to
```
flatten(response.problem.getResults().as_CompositeInstruction())
```

I'll submit a PR with the change.

**Comment by johnwason** [comment]
This should be fixed
