### ISSUE TITLE
Unable To Move Prismatic Joint in Viewer

### ISSUE THREAD

**Issue by johnboggess** [tesseract-robotics/tesseract_python#38]
Hello,

I have found when attempting to move a prismatic joint on the viewer via TesseractViewer.update_joint_positions() or TesseractViewer.update_trajectory() the viewer will not move that joint. It will also will not move any revolute joints while told to move a prismatic joint.

I have noticed in the developer tools console I am getting the following error
>Error: Unknown joint type
>    at app.js:273:27
>    at Array.forEach (<anonymous>)
>    at TesseractViewer.trajectoryToAnimation (app.js:239:21)
>    at TesseractViewer.setTrajectory (app.js:228:25)
>    at TesseractViewer.updateTrajectory (app.js:200:18)

After looking at the app.js I see in the trajectoryToAnimation function that it checks for joint type 2 for prismatic joints. However, when looking at the screen graph, as well as the .gltf file, I can see that the prismatic's joint type is 3.

Changing the switch statement in app.js to check for joint type 3 instead of 2 seems to resolve the issue.

I'm guessing this is a bug and have posted it here so you guys are aware.

**Comment by johnwason** [comment]
This should be fixed. See #44
