### ISSUE TITLE
pip version mismatch

### ISSUE THREAD

**Issue by kaiConnected** [tesseract-robotics/tesseract_python#48]
Hello,

I am a first time user of tesseract and stumbled over an error I cant fully explain.
Error message:
```
Traceback (most recent call last):
  File "/root/ws/devel/lib/tesseract_planning/planning_node.py", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/root/ws/src/tesseract_planning/src/planning_node.py", line 23, in <module>
    from tesseract_robotics_viewer import TesseractViewer
  File "/root/.local/lib/python3.8/site-packages/tesseract_robotics_viewer/__init__.py", line 1, in <module>
    from .tesseract_viewer import *
  File "/root/.local/lib/python3.8/site-packages/tesseract_robotics_viewer/tesseract_viewer.py", line 21, in <module>
    from tesseract_robotics_viewer.tesseract_env_to_gltf import tesseract_env_to_gltf, tesseract_env_to_glb
  File "/root/.local/lib/python3.8/site-packages/tesseract_robotics_viewer/tesseract_env_to_gltf.py", line 28, in <module>
    from tesseract_robotics.tesseract_command_language import isStateWaypoint, isMoveInstruction
ImportError: cannot import name 'isStateWaypoint' from 'tesseract_robotics.tesseract_command_language' (/root/.local/lib/python3.8/site-packages/tesseract_robotics/tesseract_command_language/__init__.py)
```

I installed tesseract according to the installation instructions with following lines: 
```
sudo apt install python3-pip python3-numpy
python3 -m pip install -U pip
python3 -m pip install --user  tesseract_robotics tesseract_robotics_viewer
```

After looking at the commit history of this repository I belief that there is a version mismatch with these two pip libraries.
In the latest release 0.2.2 the import line mentioned in the error message has been changed, but it is still in the file downloaded with the pip command.  Since this release was made only "tesseract_robotics" has been updated on pip. I therefore belief, that the "tesseract_robotics_viewer" needs to be updated on pip.

As I am a first time user of tesseract I might have made some other mistake, which would make this report unnecessary, but I couldn't find another explanation for this error.

(In case it is relevant: This error occurred inside of a docker container running Ubuntu 20.04.)

I would appreciate any help or response, and thank you for developing this fantastic open source project.

Best regards,
Kai

**Comment by johnwason** [comment]
Hi @kaiConnected , it looks like we missed updating the pip package. Please try again now!

**Comment by kaiConnected** [comment]
Hello,
sorry for the late answere I was on leave over the last week.
The problem seems to be fixed, thank you!
