### ISSUE TITLE
TaskComposerPluginFactory constructor is not compatible with string input

### ISSUE THREAD

**Issue by dave992** [tesseract-robotics/tesseract_python#56]
I am unable to construct a `TaskComposerPluginFactory` using a string as input:

```python
import os

from tesseract_robotics import tesseract_common
from tesseract_robotics.tesseract_task_composer import TaskComposerPluginFactory

TESSERACT_SUPPORT_DIR = os.environ["TESSERACT_RESOURCE_PATH"]
TESSERACT_TASK_COMPOSER_DIR = os.environ["TESSERACT_TASK_COMPOSER_CONFIG_FILE"]

TASK_COMPOSER_PLUGIN_YAML = r"config/task_composer_plugins.yaml"

tesseract_common.setLogLevel(tesseract_common.CONSOLE_BRIDGE_LOG_DEBUG)

config_path = TESSERACT_TASK_COMPOSER_DIR + TASK_COMPOSER_PLUGIN_YAML
factory = TaskComposerPluginFactory(config_path)
```

I get the following error:
```bash
You can set logging level with TRAJOPT_LOG_THRESH. Valid values: FATAL ERROR WARN INFO DEBUG TRACE. Defaulting to ERROR
Traceback (most recent call last):
  File "/home/samxl/workspaces/tesseract_ws/src/tesseract_playground/task_composer.py", line 16, in <module>
    factory = TaskComposerPluginFactory(config_path)
  File "/home/samxl/.local/lib/python3.8/site-packages/tesseract_robotics/tesseract_task_composer/tesseract_task_composer_python.py", line 1958, in __init__
    _tesseract_task_composer_python.TaskComposerPluginFactory_swiginit(self, _tesseract_task_composer_python.new_TaskComposerPluginFactory(*args))
RuntimeError: operator[] call on a scalar
```

If I look at the `TaskComposerPluginFactory`, I find references to a constructor using a string as input and would've expected this to also be accepted. 

For now, I will work around this by using a `tesseract_common::FilesystemPath` object as input.

**Comment by dave992** [comment]
The relevant constructors that I found for the `TaskComposerPluginFactory` are:

***Overload 2:***
Load plugins from file path
:type config: path
:param config: The config file path

***Overload 3:***
Load plugins from string
:type config: string
:param config: The config string

I think the `path` refers to `tesseract_common::FilesystemPath` which is a wrapper for `boost::filesystem::path` based on the documentation. Would it be possible to have this compatible with Python `patlib.Path`?
The overload for the `path` object would also imply

**Comment by johnwason** [comment]
The use of FilesystemPath is to select the correct overload of the function/constructor. It is wrapping boost::filesystem::path. Using Pathlib would add more unnecessary complexity from these low level wrappers.

**Comment by dave992** [comment]
Perhaps exclude the string overload from the wrapper then.

**Comment by johnwason** [comment]
The string constructor allows for the use of a string containing the yaml text without needing to open a file.

**Comment by dave992** [comment]
Ah, the third overload is a _YAML string_. Sounds like perfect info for the docstring of the overload, although out of scope for this issue 😉

**Comment by johnwason** [comment]
The docstring is generated from the C++ doxygen comments in the upstream repository.  Pull requests are always appreciated.
