### ISSUE TITLE
The viewer can not display the marker.

### ISSUE THREAD

**Issue by leiyu2023** [tesseract-robotics/tesseract_python#66]
env：
win11
viewer: 0.2.5

I successfully displayed the robotic arm in the viewer and attempted to add line segments using the code below. However, after running the code, the line segments are not being displayed in the viewer.
```
viewer = TesseractViewer()
viewer.update_environment(t_env, [0, 0, -10])
viewer.start_serve_background() 
viewer.add_lines_marker([[0, 0, 0], [10, 10, 10]], color=[[220, 20, 60, 1]],update_now=True)

```

![image](https://github.com/tesseract-robotics/tesseract_python/assets/137389182/228b30ac-4e10-4e6f-b1c6-9b0e64bf68ee)

@johnwason  
This problem has been bothering me for some time.Can you give me some suggestions？

**Comment by johnwason** [comment]
By default the marker will be added to the "world" link. It looks like your URDF file does not have a "world" link, so it is not able to add to the scene.

Try something like:

```
viewer.add_lines_marker([[0, 0, 0], [10, 10, 10]], color=[[220, 20, 60, 1]],update_now=True,parent_link="my_link")
```

where `my_link` is replaced with a valid link name in your URDF.

**Comment by leiyu2023** [comment]
Thanks to your suggestion, this issue has been effectively resolved.
